export const FUGLE_TRADE_INSTANCE = Symbol('FUGLE_TRADE_INSTANCE');
export const FUGLE_TRADE_OPTIONS = Symbol('FUGLE_TRADE_OPTIONS');
export const STREAMER_LISTENER_METADATA = Symbol('STREAMER_LISTENER_METADATA');
